package com.resonance.resources

const val SplashScreenIconDescription = "Splash Screen Image"
const val DDXAcronym = "DDX"
const val ExclamationPoint = "!"
const val SplashScreenRightPartText = " Fitness"
const val FirstOnboardingImage = "First Onboarding Image"
const val BaseContainerImage = "Background Image"
const val NextButtonCaption = "Далее"
const val OtherOnboardingFirstCaption = "Найдите\nтренировку, которая\nподходит именно вам."
const val OtherOnboardingSecondCaption = "Тренируйтесь и\nполучайте отличные\nрезультаты."
const val OtherOnboardingThirdCaptionOne = "Давайте заниматься\nспортом и вести здоровый\nобраз жизни вместе с "
const val OtherOnboardingThirdCaptionTwo = "Давайте подберем упражнения по\nвашим параметрам."
const val OtherOnboardingLatinCaption = "Lorem ipsum dolor sit amet consectetur.\n Enim tellus pellentesque sit non nisi."
const val WelcomeScreenMainCaption = "Создайте аккаунт\nили войдите анонимно"
const val WelcomeScreenAdditionalCaption = "Создайте учетную запись, чтобы\nполучить полный доступ"
const val CreateAccountButtonCaption = "Создать аккаунт"
const val LaterButtonCaption = "Позже"
const val LoginScreenMainCaption = "Электронная почта"
const val LoginScreenAdditionalCaption = "Нам нужен адрес электронной почты.\nМы определенно не будем отправлять\nспам-сообщения."
const val PrivacyPolicy = "Продолжая, принимаете нашу Политику "
const val PrivacyPolicySecond = "конфиденциальности и условия использования"
const val Email = "Email"
const val Next = "Далее"
const val LogInAnonymously = "Войти анонимно"
